name: This workflow will be called
on:
  workflow_call:
    inputs:
      num1:
        type: number
        required: true
        description: "First Number"
        default: 0
      num2:
        type: number
        required: true
        description: "Second Number"
        default: 0

  workflow_dispatch:
    inputs:
      num1:
        type: number
        required: true
        description: "First Number"
        default: 0
      num2:
        type: number
        required: true
        description: "Second Number"
        default: 0
jobs:
  FirstJob:
    runs-on: ubuntu-slim
    steps:
    - name: Add em all
      run: |
        echo " $(( ${{inputs.num1}} + ${{inputs.num2}} ))"
